name: Generate SBOM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX
        run: npm install -g @cyclonedx/bom

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v3
        with:
          name: juice-shop-sbom
          path: sbom.json
